[workspace]
resolver = "2"
members = [
    "src/rust"
]

[workspace.package]
version = "0.1.0"
authors = ["Frazer McLean <frazer@frazermclean.co.uk>"]
edition = "2021"
publish = false
rust-version = "1.65"

[workspace.dependencies]
pyo3 = { version = "0.21", features = ["abi3"] }
