[build-system]
requires = ["setuptools", "setuptools-rust"]
build-backend = "setuptools.build_meta"

[project]
name = "crabwalk"
version = "0.1"
requires-python = ">=3.7"
license = { text = "MIT" }
dependencies = []
authors = [
    { name = "Frazer McLean", email = "frazer@frazermclean.co.uk" }
]

[project.optional-dependencies]
docs = [
    "furo",
    "myst-parser",
    "sphinx",
    "doc8",
]
test = [
    "pytest",
]

[tool.isort]
profile = "black"
known_first_party = ["crabwalk"]

[tool.doc8]
ignore-path = "docs/_build/"
