[build-system]
requires = ["setuptools", "setuptools-rust"]
build-backend = "setuptools.build_meta"

[project]
name = "crabwalk"
version = "0.1"
requires-python = ">=3.7"
license = { text = "MIT" }
dependencies = []
authors = [
    { name = "Frazer McLean", email = "frazer@frazermclean.co.uk" }
]

[tool.isort]
profile = "black"
known_first_party = ["crabwalk"]
