---
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          rustc --version
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade tox tox-gh-actions

      - name: "Run tox targets for ${{ matrix.python-version }}"
        run: "python -m tox"

  msrv:
    name: "Python ${{ matrix.python.version }} with Rust ${{ matrix.rust-version }}"
    runs-on: "ubuntu-latest"

    strategy:
      fail-fast: false
      matrix:
        python:
          - { version: "3.8", toxenv: "py38" }
          - { version: "3.12", toxenv: "py312" }
        rust-version: ["1.63.0"]

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python.version }}"
      - uses: dtolnay/rust-toolchain@e645b0cf01249a964ec099494d38d2da0f0b349f
        with:
          toolchain: ${{ matrix.rust-version }}
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          rustc --version
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade tox
      - name: "Run tox"
        env:
          TOXENV: ${{ matrix.python.toxenv }}
        run: "python -m tox"
